### ISSUE TITLE
Does not supply optimal accept header to the Data Holder status endpoint

### ISSUE THREAD

**Issue by pcurtisrab** [Regional-Australia-Bank/ADR-Gateway#19]
Supplied:

```
Accept: application/json, text/plain, */*
```

Expected:
```
Accept: application/json
```

Specification says:

> If specified, the media type must be set to application/json, unless otherwise specified in the resource end point standard. \n\n If set to an unacceptable value the holder must respond with a 406 Not Acceptable. If not specified, or a wildcard (/) is provided, the default media type is application/json.

For maximum interoperability, we will set to application/json.

**Comment by mattp-rab** [comment]
Good catch!

**Comment by pcurtisrab** [comment]
Solved with https://github.com/Regional-Australia-Bank/ADR-Gateway/commit/dc254a1c44a53502978ca0bacdf48a84fe8eb449

Header is now explicit. Mock Dataholder is adapted to require accept: application/json
