### ISSUE TITLE
UpdateRegistration fails for second software product

### ISSUE THREAD

**Issue by pcurtisrab** [Regional-Australia-Bank/ADR-Gateway#38]
I can go through the entire consent flow OK with software product 1 no probs. But then with software product 2, the mock DH throws an error because Dr G tries to update registration with it because Dr G has the SSA of software product 1 instead of 2. Tracing this back, it gets it from cache. This is because the cache id logic is not correctly incorporating the software product id into the cache id. So caches for both SSAs have the same name; ‘SoftwareStatementAssertion_undefined’. This is because the parameter defined in the YML file for SSA doesn’t actually exist. In this case, the parameter is defined as ‘SoftwareProductKey’, whereas the object only contains ‘SoftwareProductId’.

**Comment by pcurtisrab** [comment]
Ideally we would have an automated test case for the scenario involving multiple software products.
However, this could be quite a complicated case. If time does not allow, we may just need to solve for cache being named `undefined`.

**Comment by mattp-rab** [comment]
This looks to have resolved the underlying issue. Nice work!
