### ISSUE TITLE
Housekeeper overwrites DH client ID after explicit dynamic client registration

### ISSUE THREAD

**Issue by NilsFrkal** [Regional-Australia-Bank/ADR-Gateway#54]
Hi,

I have noticed that the housekeeper for the DynamicClientRegistration triggers a new registration request which overwrites a previous explicit registration request as the DataHolderRegistrationManager cache does not get updated by /idp/register call. Is this by design? 

The problem with this is that the clientId return by the /idp/register API call can't be used in subsequent maintenance requests.

To reproduce:

1. Get Client Token from CDR Register (my own helper API)

2. Get Software Statement Assertion /v1/banking/data-recipients/brands/:dataRecipientBrandId/software-products/:softwareProductId/ssa

3. Create Dynamic Client Registration request DCR (my own helper API)

4. Register Software at Data Holder using DCR /idp/register -> returns clientId

-> doesn't update DataHolderRegistrationManager cache and no db entry (sandbox adr.sqlite)

Housekeeper gets triggered at interval

-> checks DataHolderRegistrationManager cache and can't find registered productID

-> generates new DCR which creates a new clientID and sets status of record above to DELETED

-> updates DataHolderRegistrationManager cache and db

Could you please advise if this works as expected? Thank you very much.

Best, Nils

**Comment by pcurtisrab** [comment]
Hi @NilsFrkal,

In step 1 and 3, is it ADR Backend that is doing DCR or are you using your own code to it? (Not sure what you mean by your own helper API.). Also, is this on a clean DB?

The central decision is expressed here:

https://github.com/Regional-Australia-Bank/ADR-Gateway/blob/83bfae6676c4f5f33b74f432fb2c7e088135fd47/src/Common/Connectivity/DependencyGraph.generated.ts#L404

`CurrentClientRegistration` is run first, to get any existing details from the database (`RegistrationManager`). `DhNewClientRegistration` will be executed if and only if the database did not return an object.

So the actual behaviour of the housekeeper is to not check a cache, but to check the database directly (`DataHolderRegistrationManager` is not a cache interface but a database interface).

It looks like this would be the core issue:

> doesn't update DataHolderRegistrationManager cache and no db entry (sandbox adr.sqlite)

Are you able to set breakpoints and confirm that this code is not being run in your reproduction step 4?:
`. https://github.com/Regional-Australia-Bank/ADR-Gateway/blob/83bfae6676c4f5f33b74f432fb2c7e088135fd47/src/Common/Connectivity/Evaluators/DynamicClientRegistration.ts#L285
2. https://github.com/Regional-Australia-Bank/ADR-Gateway/blob/83bfae6676c4f5f33b74f432fb2c7e088135fd47/src/Common/Entities/DataHolderRegistration.ts#L119

Even better, if you can use the postman collection as a basis and step through calling the ADR Backend endpoints to create the registration, and copy the requests and responses here, that would be beneficial. This is the way that ADR-Gateway is designed to be used -- as a webservice and a single access point for accessing the CDR ecosystem as a data recipient. For what it's worth, a version 2 of Dr. G might expose the APIs as a node.JS package for consumption in your own service implementation.

**Comment by NilsFrkal** [comment]
Thanks a lot for your response, this makes sense. The "mistake" I made was calling the /register API from Postman directly (bypassing ADR Gateway and passing the DCR JWT to the dataholder endpoint). In this case the housekeeper will generate a new registration request as described above. I have now moved to DhNewClientRegistration via ADR Gateway and this creates the required entries. Thanks again.
